bey_frontend/project/server/models.py
# project/server/models.py


import datetime

from flask import current_app

from project.server import db, bcrypt


class User(db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String(255), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    registered_on = db.Column(db.DateTime, nullable=False)
    admin = db.Column(db.Boolean, nullable=False, default=False)

    def __init__(self, email, password, admin=False):
        self.email = email
        self.password = bcrypt.generate_password_hash(
            password, current_app.config.get("BCRYPT_LOG_ROUNDS")
        ).decode("utf-8")
        self.registered_on = datetime.datetime.now()
        self.admin = admin

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id

    def __repr__(self):
        return "<User {0}>".format(self.email)

bey_frontend/project/server/user/forms.py
# project/server/user/forms.py


from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email, Length, EqualTo


class LoginForm(FlaskForm):
    email = StringField("Email Address", [DataRequired(), Email()])
    password = PasswordField("Password", [DataRequired()])


class RegisterForm(FlaskForm):
    email = StringField(
        "Email Address",
        validators=[
            DataRequired(),
            Email(message=None),
            Length(min=6, max=40),
        ],
    )
    password = PasswordField(
        "Password", validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        "Confirm password",
        validators=[
            DataRequired(),
            EqualTo("password", message="Passwords must match."),
        ],
    )

bey_frontend/project/__init__.py
# project/__init__.py

bey_frontend/project/server/__init__.py
# project/server/__init__.py


import os

from flask import Flask, render_template
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from flask_debugtoolbar import DebugToolbarExtension
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate


# instantiate the extensions
login_manager = LoginManager()
bcrypt = Bcrypt()
toolbar = DebugToolbarExtension()
bootstrap = Bootstrap()
db = SQLAlchemy()
migrate = Migrate()


def create_app(script_info=None):

    # instantiate the app
    app = Flask(
        __name__,
        template_folder="../client/templates",
        static_folder="../client/static",
    )

    # set config
    app_settings = os.getenv(
        "APP_SETTINGS", "project.server.config.DevelopmentConfig"
    )
    app.config.from_object(app_settings)

    # set up extensions
    login_manager.init_app(app)
    bcrypt.init_app(app)
    toolbar.init_app(app)
    bootstrap.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)

    # register blueprints
    from project.server.user.views import user_blueprint
    from project.server.main.views import main_blueprint

    app.register_blueprint(user_blueprint)
    app.register_blueprint(main_blueprint)

    # flask login
    from project.server.models import User

    login_manager.login_view = "user.login"
    login_manager.login_message_category = "danger"

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.filter(User.id == int(user_id)).first()

    # error handlers
    @app.errorhandler(401)
    def unauthorized_page(error):
        return render_template("errors/401.html"), 401

    @app.errorhandler(403)
    def forbidden_page(error):
        return render_template("errors/403.html"), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template("errors/404.html"), 404

    @app.errorhandler(500)
    def server_error_page(error):
        return render_template("errors/500.html"), 500

    # shell context for flask cli
    @app.shell_context_processor
    def ctx():
        return {"app": app, "db": db}

    return app

bey_frontend/project/server/main/__init__.py
# project/server/main/__init__.py

bey_frontend/project/server/main/views.py
# project/server/main/views.py


from flask import render_template, Blueprint


main_blueprint = Blueprint("main", __name__)


@main_blueprint.route("/")
def home():
    return render_template("main/home.html")


@main_blueprint.route("/about/")
def about():
    return render_template("main/about.html")

bey_frontend/project/server/user/__init__.py
# project/server/user/__init__.py

bey_frontend/project/server/user/views.py
# project/server/user/views.py


from flask import render_template, Blueprint, url_for, redirect, flash, request
from flask_login import login_user, logout_user, login_required

from project.server import bcrypt, db
from project.server.models import User
from project.server.user.forms import LoginForm, RegisterForm


user_blueprint = Blueprint("user", __name__)


@user_blueprint.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(email=form.email.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()

        login_user(user)

        flash("Thank you for registering.", "success")
        return redirect(url_for("user.members"))

    return render_template("user/register.html", form=form)


@user_blueprint.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
            user.password, request.form["password"]
        ):
            login_user(user)
            flash("You are logged in. Welcome!", "success")
            return redirect(url_for("user.members"))
        else:
            flash("Invalid email and/or password.", "danger")
            return render_template("user/login.html", form=form)
    return render_template("user/login.html", title="Please Login", form=form)


@user_blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out. Bye!", "success")
    return redirect(url_for("main.home"))


@user_blueprint.route("/members")
@login_required
def members():
    return render_template("user/members.html")

bey_frontend/project/client/templates/_base.html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <title>{{ config.APP_NAME }}{% block title %}{% endblock %}</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{{url_for('static', filename='main.css')}}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
  </head>

  <body>

    {% include 'header.html' %}

    <div class="site-content">
      <div class="container">

        <!-- messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <br>
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
              {{message}}
            </div>
            {% endfor %}
          </div>
        </div>
        {% endif %}
        {% endwith %}

        <!-- child template -->
        {% block content %}{% endblock %}

        <br>

        <!-- errors -->
        {% if error %}
          <p class="error"><strong>Error:</strong> {{ error }}</p>
        {% endif %}

      </div>
    </div>

    <br><br>

    {% include 'footer.html' %}

    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>
    {% block js %}{% endblock %}

  </body>
</html>

bey_frontend/project/client/templates/footer.html
<footer>
  <nav class="navbar fixed-bottom navbar-light bg-light">
    <div class="container">
      <small>
        <span>©
          <a href="http://mherman.org">Michael Herman</a>
        </span>
      </small>
    </div>
  </nav>
</footer>

bey_frontend/project/client/templates/header.html
<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <!-- Navbar Brand -->
    <a class="navbar-brand" href="{{ url_for('main.home') }}">{{ config.APP_NAME }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <!-- Main Navigation -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.members') }}">Members</a>
        </li>
        {% endif %}
      </ul>
      <!-- Login/Logout -->
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          {% if current_user.is_authenticated %}
          <a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a>
          {% else %}
          <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>

bey_frontend/project/client/templates/main/about.html
{% extends "_base.html" %}
{% block content %}

<div class="body-content">
  <div>
    <h1>About</h1>
    <hr><br>
    <p>Add some content here!</p>
  </div>
</div>

{% endblock %}

bey_frontend/project/client/templates/main/home.html
{% extends "_base.html" %}
{% block content %}

<div>
  <h1>Welcome!</h1>
  <hr><br>
  <p>Add some content here!</p>
</div>

{% endblock %}

bey_frontend/project/client/templates/user/login.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

  <header class="content-header">
    <h1>Login</h1>
    <hr><br>
  </header>

  <br>

  <form class="form" role="form" method="post" action="">
    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}

    <div class="col-lg-4 col-sm-4">
      {{ wtf.form_field(form.email) }}
      {{ wtf.form_field(form.password) }}

      <button class="btn btn-success" type="submit">Sign In!</button>
      <br><br>
      <p>Need to <a href="{{ url_for('user.register') }}">Register</a>?</p>
    </div>
  </form>

{% endblock %}

bey_frontend/project/client/templates/user/members.html
{% extends "_base.html" %}
{% block content %}

  <h1>Welcome, <em>{{ current_user.email }}</em>!</h1>
  <h3>This is the members-only page.</h3>

{% endblock %}

bey_frontend/project/client/templates/user/register.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

  <header class="content-header">
    <h1>Register</h1>
    <hr><br>
  </header>

  <br>

  <form class="form" role="form" method="post" action="">
    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}

    <div class="col-lg-4 col-sm-4">
      {{ wtf.form_field(form.email) }}
      {{ wtf.form_field(form.password) }}
      {{ wtf.form_field(form.confirm) }}

      <button class="btn btn-success" type="submit">Register!</button>
      <br><br>
      <p>Already have an account? <a href="{{ url_for('user.login') }}">Sign in</a>.</p>
    </div>
  </form>

{% endblock %}